"use client"
import type { Metadata } from "next";
import { Fira_Code, Open_Sans } from "next/font/google";
import "./globals.css";

const fira = Fira_Code({
  variable: "--font-fira",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          
      <body
        className={`${fira.variable} ${openSans.variable} antialiased bg-black text-white relative w-full h-full`}
      >

      <main className={'relative z-10'}>
          {children}
      </main>
        
      </body>
    </html>
  );
}
