"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import CircularText from "@/components/CircularText";
import TargetCursor from "@/components/TargetCursor";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[#111124] text-gray-400 relative w-full h-full`}
      >
      <div className={'fixed inset-0 -z-10'}>
          {/*<LiquidEther
              colors={['#5227FF', '#FF9FFC', '#B19EEF']}
              mouseForce={20}
              cursorSize={100}
              isViscous={false}
              viscous={30}
              iterationsViscous={32}
              iterationsPoisson={32}
              resolution={0.5}
              isBounce={false}
              autoDemo={true}
              autoSpeed={0.5}
              autoIntensity={2.2}
              takeoverDuration={0.25}
              autoResumeDelay={3000}
              autoRampDuration={0.6}
          />*/}
      </div>

      <main className={'relative z-10'}>
          <TargetCursor
              spinDuration={2}
              hideDefaultCursor={true}
          />
          {children}
      </main>
        <div className={'absolute top-4 right-4'}>
            Boutton
        </div>
      </body>
    </html>
  );
}
